CREATE TABLE IF NOT EXISTS users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  playername TEXT,
  username TEXT UNIQUE,
  password TEXT,
  role TEXT DEFAULT 'player',
  loop1_completed INTEGER DEFAULT 0,
  loop2_completed INTEGER DEFAULT 0,
  loop3_completed INTEGER DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS logs (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT,
  action TEXT,
  timestamp DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- teams table for loop2
CREATE TABLE IF NOT EXISTS teams1 (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT,
  token TEXT UNIQUE,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE IF NOT EXISTS teams2 (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT,
  token TEXT UNIQUE,
  is_bad_team INTEGER DEFAULT 0, -- good=0, bad=1
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);